name: Release

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: microservice_framework_tests
        ports:
          - 3306:3306
        # Set health checks to wait until mysql has started
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --verbosity normal
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432

          MYSQL_ROOT_PASSWORD: root
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: microservice_framework_tests
      - name: Clean
        run: dotnet clean ./MicroserviceToolkit.sln
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Pack
        run: dotnet pack ./microservicetoolkit/mpstyle.microservice.toolkit.csproj -c Release
      - name: Release
        run: dotnet nuget push ./microservicetoolkit/bin/Release/mpstyle.microservice.toolkit.${GITHUB_REF#refs/tags/}.nupkg --api-key ${{ secrets.NUGET_GALLERY_TOKEN }} --source https://api.nuget.org/v3/index.json
